# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: demopool

steps:
- task: Cache@2
  inputs:
    key: 'node | "$(Agent.OS)"'
    path: 'node_modules'
  displayName: 'Cache'

- script: yarn install
  displayName: 'Install dependencies'

#- script: CI=true yarn test
#  displayName: 'Run tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'node_modules'
    artifact: 'node_modules'
    publishLocation: 'pipeline'
